### ISSUE TITLE
Extract color lib to own module

### ISSUE THREAD

**Issue by StephanHoyer** [PimpTrizkit/PJs#1]
Just found you color modification function via google. Great thing, just what I needed.

Would be great to have it as a standalone package (npm). It would also be great to have it with a more permissive licence (e. G. MIT)

Thanks for your work.

**Comment by PimpTrizkit** [comment]
Thank You!  That color function, called `pSBC`, was a long time in development actually. Of course, there were long times of nothing, then one day, a new version..lol... but it was a few years.

Please excuse my ignorance for the issues you have posted here. But I am not all that familiar with various forms of integration or whatnot you may be asking about.

* npm - I just now did a quick google. I looks like another repository?  I'm not sure what it provides different from GitHub.  BUT, these functions (including `pSBC`... the color one) are not meant to be coming from a linked source. They were written to be used as copy-and-pasted directly into the html. To prevent excessive net calls for loading resources. So, I'm not sure what a JS package would do for me.. especially one that is only for the color function `pSBC`. When its easier/faster to just copy and paste the few lines of code. At least, that is how my limited mind sees it! haha, maybe you can teach me a thing or two, it sounds like it, heh.

* A More Permissive Licence - This went right over my head, sorry. But, whats wrong with the GNU? Or I am probably misunderstanding... well... everything here.

* The title of your message reads "Extract color lib to own module" - But you didn't seem to *mention* anything about extracting colors. And, to me, going off the title alone, is unclear. Extracting from where? to where? in what formats? in what type? And what module? where? I don't see a module (looks under the table), hehe. And `pSBC` (the color function) doesn't, necessarily, do extractions... whatever that is... but it does have a Rip function. However, the object created by the rip was arbitrary and of my own design. I'm not sure, but are you referencing this feature?

PT

**Comment by marcovo** [comment]
Regarding the licensing, I was looking to include the pSBC code (or, a rewrite of version 3.1 in PHP) in a MIT project of mine. Sadly, as it is GPL 3.0 licensed, I'm not able to use it in the MIT project.

If it were licensed MIT or LGPL, it would be possible to include in an MIT project.

Are you open to reconsidering the licensing, or did you purposefully chose the GPL license?

**Comment by PimpTrizkit** [comment]
Hello! Thanks for your interest in my function.

I do like the strong copyleft that the GPL3.0 provides, I believe code should be free to and by all. 
And at all times and situations and ways of distribution.

But, per your request, I changed it to LGPL3.0.

I would like to highly request a copy of your final PHP version of the pSBC code. As well, include to whom accreditation should be given. I will add this to the current PJs/pSBC project and give credit where credit is due. Also, can you provide an online link to your project (or else, information relevant to your project) which can be shared, if possible.

Enjoy the code and I look forward to hearing back from you!

PT

**Comment by PimpTrizkit** [comment]
This has been added to npm.

https://www.npmjs.com/package/shade-blend-color

PT
