### ISSUE TITLE
pSBC port to php

### ISSUE THREAD

**Issue by marcovo** [PimpTrizkit/PJs#2]
I thought I could email to the generic github e-mail address, but apparently I can't, so here is my e-mail I mentioned here: https://github.com/PimpTrizkit/PJs/issues/1#issuecomment-411647661

-------

The code on your PJs repository seems somewhat scrambled, I guess this is a minified version and not the original?

Do you have an original version of the pSBC.js code for me? That would make converting to PHP considerably easier ;) .
By the way, as PHP code often is not minified, this would mean that your original source converted to PHP will appear on the internet. I don't know whether you'd have something against this, but seeing as you have not published your original code in the repository you may dislike your source being available or something like that? Just saying...

I guess I could create a PHP repository with the translated code, referring back to your repository as source reference (including a valid copyright statement of course)?

**Comment by PimpTrizkit** [comment]
Sorry for the delayed response. You can see the evolution of the code here: https://stackoverflow.com/questions/5560248/programmatically-lighten-or-darken-a-hex-color-or-rgb-and-blend-colors/13542669#13542669

There was no other source code. As mentioned in that OP (maybe in the comments, maybe on different answers on that same OP), the first concern was size and speed. The second concern was accuracy. Using a HSL method would probably be more accurate, but much slower and larger. Readability was not a concern, it was meant for distribution/end usage. As is the theme of my library. It's all ready to go!  I did some weird stuff to make it as concise as possible and as small as possible (well, when I say "concise" I mean "brief" and "comprehensive", not "clear" nor "easy to understand", lol). A couple examples: For conciseness, I put most of the real work on one line, its a little confusing, but its a powerful line. Nested ternary statements, recycled and renamed variables all over the place. And so for size,  I renamed `parseInt` and `Math.round` to a single character. I recycled variables (meaning, I re-used them for different things) keeping the stack down to 6 vars, I think it is. And then those nested ternary statements save a ton of space and possibly native browser code can make that run more efficient. Also, the building of the final color, most of it is done while building the string, and the final result is passed in only once to the converter. (`toString(16)`)

Each version (seen on StackOverflow) was written just as you see it. No actual minifier was used on the code. `pSBC` on GitHub is actually version 3.1 on StackOverflow. If you take notice of Version 2, you will see a PHP version of that. However, the original Version 2 does not include all the bells and whistles, only simple color shading/blending. I would think you could start there, then add in any extras you might want. (ie. Error Checking, Alphas, 3/4 Digit Hex Color input, RGB2Hex / Hex2RGB Conversions, secondary global function for ripping.)

Yes, build that repository my friend!

PT

**Comment by marcovo** [comment]
Hi,

I've created a PHP repo here:
https://gitlab.com/marcovo/shade-blend-convert

It guess you know the entire code by heart, because interpreting these nested ternary operators was quite an exercise :P . I've ported the code to PHP, with some minor edits. Overall the interface has remained the same.

Regards,
Marco
